api = "0.2"

[buildpack]
id = "heroku/jvm"
version = "0.1"
name = "JVM"

  [publish.Ignore]
  files = [
    "etc/",
    "spec/",
    "test/",
    ".gitignore",
    ".github/",
    ".travis.yml",
    "circle.yml",
    "hatchet.json",
    "Gemfile",
    "Gemfile.lock"
  ]

[[stacks]]
id = "heroku-18"

[[stack]]
id = "heroku-20"

# this is to allow testing of other stack compatibility and is not a guarantee
[[stacks]]
id = "io.buildpacks.stacks.bionic"
